Repository openshift/online-hibernation, pull requests merged in 2018-03, with the labels that each got.

#49 Check status after deployment
  ansible/roles/oso_hibernation/tasks/main.yml
Labels: lgtm, size/XS

#50 Cleanup template file with osoh_uninstall
  ansible/roles/oso_hibernation/tasks/uninstall.yml
Labels: lgtm, size/XS

#51 Ansible-ensure template directory exists
  ansible/roles/oso_hibernation/defaults/main.yml
  ansible/roles/oso_hibernation/tasks/main.yml
Labels: size/XS

#56 fix panic when auto-idler can't access prometheus
  pkg/idling/autoidle.go
  pkg/idling/autoidle_test.go
Labels: lgtm, size/M

#54 add openshift projects to list of excluded ns
  ansible/roles/oso_hibernation/defaults/main.yml
Labels: lgtm, size/XS
