Repository openshift/online-hibernation, pull requests merged in 2018-04, with the labels that each got.

#58 Use namespace label to include projects for online-hibernation
  ansible/roles/oso_hibernation/defaults/main.yml
  ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2
  cmd/hibernate/cmd.go
  pkg/cache/cache.go
  pkg/cache/resource-store.go
  pkg/cache/resource-store_test.go
  pkg/forcesleep/forcesleep_test.go
  pkg/idling/autoidle.go
  pkg/idling/autoidle_test.go
Labels: lgtm, size/L

#59 edit idle-threshold=1 and idle_query=24h
  ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2
Labels: approved, lgtm, size/XS

#60 merge master into stg
  ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2
Labels: size/XS

#61 merge stg into prod
  ansible/roles/oso_hibernation/templates/hibernation-template.yaml.j2
Labels: size/XS
